# Netlify Configuration for Static Export (Fallback Solution)
# Use this netlify.toml if the standard Next.js build has data loading issues

[build]
  base = "frontend"
  command = "npm run build"
  publish = "out"  # Changed to 'out' for static export

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  NPM_FLAGS = "--legacy-peer-deps"

# Headers for security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"

[[headers]]
  for = "/version.json"
  [headers.values]
    Content-Type = "application/json"
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# SPA routing - redirect all to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
