# Netlify Configuration for Anuranan Employee Portal (Serverless)

[build]
  # Frontend build settings
  base = "frontend"
  command = "npm run build"
  publish = ".next"

[build.environment]
  # Node version
  NODE_VERSION = "18"
  # Disable Netlify's automatic Next.js detection to use plugin
  NPM_FLAGS = "--legacy-peer-deps"

# Use Netlify Next.js Plugin for proper routing
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Headers for security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Force no cache for HTML pages
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"

# Version file - always fetch fresh
[[headers]]
  for = "/version.json"
  [headers.values]
    Content-Type = "application/json"
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
    Pragma = "no-cache"

# Next.js static assets - these have hashes in filenames, safe to cache long-term
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Icons - can be cached but with shorter duration
[[headers]]
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=86400, must-revalidate"
