# Netlify Configuration for Anuranan Employee Portal

[build]
  # Frontend build settings
  base = "frontend"
  command = "npm run build"
  publish = "frontend/.next"

[build.environment]
  # Node version
  NODE_VERSION = "18"
  # Install dependencies without optional packages
  NPM_FLAGS = "--legacy-peer-deps"

# Redirect all requests to the frontend
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Backend API proxy (if you're deploying backend elsewhere)
# [[redirects]]
#   from = "/api/*"
#   to = "https://your-backend-url.com/api/:splat"
#   status = 200
#   force = true
